/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as EntriesRouteImport } from './routes/entries'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'
import { Route as AccountsNewRouteImport } from './routes/accounts.new'
import { Route as EntriesIndexRouteImport } from './routes/entries.index'
import { Route as EntriesImportRouteImport } from './routes/entries.import'
import { Route as EntriesNewRouteImport } from './routes/entries.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsInvitationsRouteImport } from './routes/settings.invitations'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as AccountsAccountIdIndexRouteImport } from './routes/accounts.$accountId.index'
import { Route as AccountsAccountIdEditRouteImport } from './routes/accounts.$accountId.edit'
import { Route as AccountsAccountIdSharingRouteImport } from './routes/accounts.$accountId.sharing'
import { Route as CategoriesCategoryIdSharingRouteImport } from './routes/categories_.$categoryId.sharing'
import { Route as EntriesEntryIdEditRouteImport } from './routes/entries.$entryId.edit'
import { Route as TagsTagIdSharingRouteImport } from './routes/tags_.$tagId.sharing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesRoute = EntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccountsRoute,
} as any)
const EntriesIndexRoute = EntriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntriesRoute,
} as any)
const EntriesImportRoute = EntriesImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => EntriesRoute,
} as any)
const EntriesNewRoute = EntriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EntriesRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsInvitationsRoute = SettingsInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const AccountsAccountIdIndexRoute = AccountsAccountIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsAccountIdRoute,
} as any)
const AccountsAccountIdEditRoute = AccountsAccountIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AccountsAccountIdRoute,
} as any)
const AccountsAccountIdSharingRoute =
  AccountsAccountIdSharingRouteImport.update({
    id: '/sharing',
    path: '/sharing',
    getParentRoute: () => AccountsAccountIdRoute,
  } as any)
const CategoriesCategoryIdSharingRoute =
  CategoriesCategoryIdSharingRouteImport.update({
    id: '/categories_/$categoryId/sharing',
    path: '/categories/$categoryId/sharing',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntriesEntryIdEditRoute = EntriesEntryIdEditRouteImport.update({
  id: '/$entryId/edit',
  path: '/$entryId/edit',
  getParentRoute: () => EntriesRoute,
} as any)
const TagsTagIdSharingRoute = TagsTagIdSharingRouteImport.update({
  id: '/tags_/$tagId/sharing',
  path: '/tags/$tagId/sharing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/entries': typeof EntriesRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tags': typeof TagsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts/new': typeof AccountsNewRoute
  '/entries/import': typeof EntriesImportRoute
  '/entries/new': typeof EntriesNewRoute
  '/settings/invitations': typeof SettingsInvitationsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/accounts/': typeof AccountsIndexRoute
  '/entries/': typeof EntriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/accounts/$accountId/edit': typeof AccountsAccountIdEditRoute
  '/accounts/$accountId/sharing': typeof AccountsAccountIdSharingRoute
  '/categories/$categoryId/sharing': typeof CategoriesCategoryIdSharingRoute
  '/entries/$entryId/edit': typeof EntriesEntryIdEditRoute
  '/tags/$tagId/sharing': typeof TagsTagIdSharingRoute
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/tags': typeof TagsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/entries/import': typeof EntriesImportRoute
  '/entries/new': typeof EntriesNewRoute
  '/settings/invitations': typeof SettingsInvitationsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/accounts': typeof AccountsIndexRoute
  '/entries': typeof EntriesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/accounts/$accountId/edit': typeof AccountsAccountIdEditRoute
  '/accounts/$accountId/sharing': typeof AccountsAccountIdSharingRoute
  '/categories/$categoryId/sharing': typeof CategoriesCategoryIdSharingRoute
  '/entries/$entryId/edit': typeof EntriesEntryIdEditRoute
  '/tags/$tagId/sharing': typeof TagsTagIdSharingRoute
  '/accounts/$accountId': typeof AccountsAccountIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/entries': typeof EntriesRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tags': typeof TagsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts/new': typeof AccountsNewRoute
  '/entries/import': typeof EntriesImportRoute
  '/entries/new': typeof EntriesNewRoute
  '/settings/invitations': typeof SettingsInvitationsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/accounts/': typeof AccountsIndexRoute
  '/entries/': typeof EntriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/accounts/$accountId/edit': typeof AccountsAccountIdEditRoute
  '/accounts/$accountId/sharing': typeof AccountsAccountIdSharingRoute
  '/categories_/$categoryId/sharing': typeof CategoriesCategoryIdSharingRoute
  '/entries/$entryId/edit': typeof EntriesEntryIdEditRoute
  '/tags_/$tagId/sharing': typeof TagsTagIdSharingRoute
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/categories'
    | '/entries'
    | '/home'
    | '/login'
    | '/reports'
    | '/settings'
    | '/tags'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/entries/import'
    | '/entries/new'
    | '/settings/invitations'
    | '/settings/users'
    | '/accounts/'
    | '/entries/'
    | '/settings/'
    | '/accounts/$accountId/edit'
    | '/accounts/$accountId/sharing'
    | '/categories/$categoryId/sharing'
    | '/entries/$entryId/edit'
    | '/tags/$tagId/sharing'
    | '/accounts/$accountId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/home'
    | '/login'
    | '/reports'
    | '/tags'
    | '/accounts/new'
    | '/entries/import'
    | '/entries/new'
    | '/settings/invitations'
    | '/settings/users'
    | '/accounts'
    | '/entries'
    | '/settings'
    | '/accounts/$accountId/edit'
    | '/accounts/$accountId/sharing'
    | '/categories/$categoryId/sharing'
    | '/entries/$entryId/edit'
    | '/tags/$tagId/sharing'
    | '/accounts/$accountId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/categories'
    | '/entries'
    | '/home'
    | '/login'
    | '/reports'
    | '/settings'
    | '/tags'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/entries/import'
    | '/entries/new'
    | '/settings/invitations'
    | '/settings/users'
    | '/accounts/'
    | '/entries/'
    | '/settings/'
    | '/accounts/$accountId/edit'
    | '/accounts/$accountId/sharing'
    | '/categories_/$categoryId/sharing'
    | '/entries/$entryId/edit'
    | '/tags_/$tagId/sharing'
    | '/accounts/$accountId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  EntriesRoute: typeof EntriesRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TagsRoute: typeof TagsRoute
  CategoriesCategoryIdSharingRoute: typeof CategoriesCategoryIdSharingRoute
  TagsTagIdSharingRoute: typeof TagsTagIdSharingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries': {
      id: '/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/entries/': {
      id: '/entries/'
      path: '/'
      fullPath: '/entries/'
      preLoaderRoute: typeof EntriesIndexRouteImport
      parentRoute: typeof EntriesRoute
    }
    '/entries/import': {
      id: '/entries/import'
      path: '/import'
      fullPath: '/entries/import'
      preLoaderRoute: typeof EntriesImportRouteImport
      parentRoute: typeof EntriesRoute
    }
    '/entries/new': {
      id: '/entries/new'
      path: '/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof EntriesNewRouteImport
      parentRoute: typeof EntriesRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/invitations': {
      id: '/settings/invitations'
      path: '/invitations'
      fullPath: '/settings/invitations'
      preLoaderRoute: typeof SettingsInvitationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/accounts/$accountId/': {
      id: '/accounts/$accountId/'
      path: '/'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AccountsAccountIdIndexRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/edit': {
      id: '/accounts/$accountId/edit'
      path: '/edit'
      fullPath: '/accounts/$accountId/edit'
      preLoaderRoute: typeof AccountsAccountIdEditRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/sharing': {
      id: '/accounts/$accountId/sharing'
      path: '/sharing'
      fullPath: '/accounts/$accountId/sharing'
      preLoaderRoute: typeof AccountsAccountIdSharingRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/categories_/$categoryId/sharing': {
      id: '/categories_/$categoryId/sharing'
      path: '/categories/$categoryId/sharing'
      fullPath: '/categories/$categoryId/sharing'
      preLoaderRoute: typeof CategoriesCategoryIdSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$entryId/edit': {
      id: '/entries/$entryId/edit'
      path: '/$entryId/edit'
      fullPath: '/entries/$entryId/edit'
      preLoaderRoute: typeof EntriesEntryIdEditRouteImport
      parentRoute: typeof EntriesRoute
    }
    '/tags_/$tagId/sharing': {
      id: '/tags_/$tagId/sharing'
      path: '/tags/$tagId/sharing'
      fullPath: '/tags/$tagId/sharing'
      preLoaderRoute: typeof TagsTagIdSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountsAccountIdRouteChildren {
  AccountsAccountIdEditRoute: typeof AccountsAccountIdEditRoute
  AccountsAccountIdSharingRoute: typeof AccountsAccountIdSharingRoute
  AccountsAccountIdIndexRoute: typeof AccountsAccountIdIndexRoute
}

const AccountsAccountIdRouteChildren: AccountsAccountIdRouteChildren = {
  AccountsAccountIdEditRoute: AccountsAccountIdEditRoute,
  AccountsAccountIdSharingRoute: AccountsAccountIdSharingRoute,
  AccountsAccountIdIndexRoute: AccountsAccountIdIndexRoute,
}

const AccountsAccountIdRouteWithChildren =
  AccountsAccountIdRoute._addFileChildren(AccountsAccountIdRouteChildren)

interface AccountsRouteChildren {
  AccountsAccountIdRoute: typeof AccountsAccountIdRouteWithChildren
  AccountsNewRoute: typeof AccountsNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsAccountIdRoute: AccountsAccountIdRouteWithChildren,
  AccountsNewRoute: AccountsNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface EntriesRouteChildren {
  EntriesImportRoute: typeof EntriesImportRoute
  EntriesNewRoute: typeof EntriesNewRoute
  EntriesIndexRoute: typeof EntriesIndexRoute
  EntriesEntryIdEditRoute: typeof EntriesEntryIdEditRoute
}

const EntriesRouteChildren: EntriesRouteChildren = {
  EntriesImportRoute: EntriesImportRoute,
  EntriesNewRoute: EntriesNewRoute,
  EntriesIndexRoute: EntriesIndexRoute,
  EntriesEntryIdEditRoute: EntriesEntryIdEditRoute,
}

const EntriesRouteWithChildren =
  EntriesRoute._addFileChildren(EntriesRouteChildren)

interface SettingsRouteChildren {
  SettingsInvitationsRoute: typeof SettingsInvitationsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsInvitationsRoute: SettingsInvitationsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  EntriesRoute: EntriesRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TagsRoute: TagsRoute,
  CategoriesCategoryIdSharingRoute: CategoriesCategoryIdSharingRoute,
  TagsTagIdSharingRoute: TagsTagIdSharingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
